[package]
name = "pico2w_blink"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = { version = "0.7", optional = true }
panic-halt = "0.2.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"